module.exports = async function (sequelize) {
	const { Person } = sequelize.models;

	const count = await Person.count();
	if (count > 0) {
		return;
	}

	const persons = [
		{
			first_name: 'Lucía',
			last_name: 'González',
			document_type: 'DNI',
			document_number: '34567890',
			birth_date: '1987-09-12',
			phone: '+54 9 11 2345 6789',
			address: {
				country: 'Argentina',
				city: 'Buenos Aires',
				neighborhood: 'Palermo',
				street: 'Cerviño',
				number: '3350',
				floor: '5',
				unit: 'B',
				additional: 'Frente al parque',
				postal_code: '1425',
				between_street_1: 'Santa Fe',
				between_street_2: 'Luis María Campos',
			},
			emergency_contact_name: 'María González',
			emergency_contact_phone: '+54 9 11 2233 4455',
		},
		{
			first_name: 'Martín',
			last_name: 'Fernández',
			document_type: 'CI',
			document_number: '1234567',
			birth_date: '1992-02-28',
			phone: '+54 9 223 555 1234',
			address: {
				country: 'Argentina',
				city: 'La Plata',
				neighborhood: 'Centro',
				street: 'Diagonal 74',
				number: '987',
				floor: '2',
				unit: 'A',
				additional: 'Oficina 201',
				postal_code: '1900',
				between_street_1: '7',
				between_street_2: '8',
			},
			emergency_contact_name: 'Ana Díaz',
			emergency_contact_phone: '+54 9 221 444 7788',
		},
		{
			first_name: 'Valentina',
			last_name: 'Pérez',
			document_type: 'DNI',
			document_number: '40876512',
			birth_date: '1984-06-30',
			phone: '+54 9 11 8765 4321',
			address: {
				country: 'Argentina',
				city: 'Rosario',
				neighborhood: 'Pichincha',
				street: 'Av. Pellegrini',
				number: '1600',
				floor: '7',
				unit: 'C',
				additional: 'Depto. C7',
				postal_code: '2000',
				between_street_1: 'Ricardo Núñez',
				between_street_2: 'Corrientes',
			},
			emergency_contact_name: 'Jorge Pérez',
			emergency_contact_phone: '+54 9 341 555 6677',
		},
		{
			first_name: 'Federico',
			last_name: 'Suárez',
			document_type: 'LC',
			document_number: '45A6789',
			birth_date: '1979-12-08',
			phone: '+54 9 223 666 9900',
			address: {
				country: 'Argentina',
				city: 'Mar del Plata',
				neighborhood: 'La Perla',
				street: 'San Martín',
				number: '1122',
				floor: null,
				unit: null,
				additional: 'Casa',
				postal_code: '7600',
				between_street_1: 'Rivadavia',
				between_street_2: 'Belgrano',
			},
			emergency_contact_name: 'Gabriela Suárez',
			emergency_contact_phone: '+54 9 223 333 2211',
		},
		{
			first_name: 'Camila',
			last_name: 'Ramírez',
			document_type: 'LE',
			document_number: '78B2345',
			birth_date: '1995-11-14',
			phone: '+54 9 11 3344 5566',
			address: {
				country: 'Argentina',
				city: 'Córdoba',
				neighborhood: 'Nueva Córdoba',
				street: 'Bv. Illia',
				number: '450',
				floor: '10',
				unit: 'D',
				additional: 'Piso 10',
				postal_code: '5000',
				between_street_1: 'Av. Poeta Lugones',
				between_street_2: 'Obispo Oro',
			},
			emergency_contact_name: 'Marta Gómez',
			emergency_contact_phone: '+54 9 351 777 8899',
		},
		{
			first_name: 'Diego',
			last_name: 'Torres',
			document_type: 'DNI',
			document_number: '29876543',
			birth_date: '1981-03-22',
			phone: '+54 9 11 5566 7788',
			address: {
				country: 'Argentina',
				city: 'Santa Fe',
				neighborhood: 'Centro',
				street: '27 de Febrero',
				number: '2700',
				floor: '3',
				unit: 'A',
				additional: 'Oficina 301',
				postal_code: '3000',
				between_street_1: 'Mendoza',
				between_street_2: 'Salta',
			},
			emergency_contact_name: 'Laura Torres',
			emergency_contact_phone: '+54 9 342 222 3344',
		},
		{
			first_name: 'Sofía',
			last_name: 'Molina',
			document_type: 'DNI',
			document_number: '51423098',
			birth_date: '1998-07-05',
			phone: '+54 9 261 888 1234',
			address: {
				country: 'Argentina',
				city: 'Mendoza',
				neighborhood: 'Ciudad',
				street: 'Arístides Villanueva',
				number: '560',
				floor: '1',
				unit: 'B',
				additional: 'Depto. 1B',
				postal_code: '5500',
				between_street_1: 'Peltier',
				between_street_2: 'Boulogne Sur Mer',
			},
			emergency_contact_name: 'Daniel Molina',
			emergency_contact_phone: '+54 9 261 444 5566',
		},
		{
			first_name: 'Martina',
			last_name: 'Cruz',
			document_type: 'OTRO',
			document_number: 'XYZ12345',
			birth_date: '1990-04-18',
			phone: '+54 9 11 9988 7766',
			address: {
				country: 'Argentina',
				city: 'Rosario',
				neighborhood: 'Centro',
				street: 'Córdoba',
				number: '2120',
				floor: '8',
				unit: 'H',
				additional: 'Departamento 8H',
				postal_code: '2000',
				between_street_1: 'San Luis',
				between_street_2: 'Dorrego',
			},
			emergency_contact_name: 'Nicolás Cruz',
			emergency_contact_phone: '+54 9 341 999 8811',
		},
		{
			first_name: 'Gonzalo',
			last_name: 'Vega',
			document_type: 'DNI',
			document_number: '87654321',
			birth_date: '1986-10-10',
			phone: '+54 9 11 1010 2020',
			address: {
				country: 'Argentina',
				city: 'Buenos Aires',
				neighborhood: 'Recoleta',
				street: 'Avenida Santa Fe',
				number: '1800',
				floor: '4',
				unit: 'D',
				additional: 'Frente al museo',
				postal_code: '1123',
				between_street_1: 'Junín',
				between_street_2: 'Uruguay',
			},
			emergency_contact_name: 'Patricia Vega',
			emergency_contact_phone: '+54 9 11 3030 4040',
		},
		{
			first_name: 'Andrés',
			last_name: 'Ramón',
			document_type: 'CI',
			document_number: '2547890',
			birth_date: '1993-05-26',
			phone: '+54 9 11 2234 5566',
			address: {
				country: 'Argentina',
				city: 'Córdoba',
				neighborhood: 'Nueva Córdoba',
				street: 'Laprida',
				number: '122',
				floor: '2',
				unit: 'C',
				additional: 'Torre A',
				postal_code: '5000',
				between_street_1: 'Ecuador',
				between_street_2: 'Ovidio Lagos',
			},
			emergency_contact_name: 'Rocío Ramírez',
			emergency_contact_phone: '+54 9 351 123 4567',
		},
		{
			first_name: 'Florencia',
			last_name: 'Sosa',
			document_type: 'DNI',
			document_number: '63214587',
			birth_date: '1991-01-09',
			phone: '+54 9 11 5566 1122',
			address: {
				country: 'Argentina',
				city: 'San Juan',
				neighborhood: 'Centro',
				street: 'Irigoyen',
				number: '341',
				floor: '1',
				unit: 'A',
				additional: 'Depto. A1',
				postal_code: '5400',
				between_street_1: 'Mitre',
				between_street_2: 'Sarmiento',
			},
			emergency_contact_name: 'Sergio Sosa',
			emergency_contact_phone: '+54 9 264 987 6543',
		},
		{
			first_name: 'María',
			last_name: 'López',
			document_type: 'DNI',
			document_number: '71234567',
			birth_date: '1989-08-01',
			phone: '+54 9 11 6655 4433',
			address: {
				country: 'Argentina',
				city: 'Neuquén',
				neighborhood: 'Centro',
				street: 'Roca',
				number: '1420',
				floor: '6',
				unit: 'B',
				additional: 'Depto. 6B',
				postal_code: '8300',
				between_street_1: 'Sarmiento',
				between_street_2: 'Alvear',
			},
			emergency_contact_name: 'Pedro López',
			emergency_contact_phone: '+54 9 299 123 9876',
		},
		{
			first_name: 'Nicolás',
			last_name: 'Márquez',
			document_type: 'DNI',
			document_number: '82456790',
			birth_date: '1983-02-17',
			phone: '+54 9 11 7788 9900',
			address: {
				country: 'Argentina',
				city: 'La Plata',
				neighborhood: 'Villa Elvira',
				street: '72',
				number: '2500',
				floor: null,
				unit: null,
				additional: 'Casa',
				postal_code: '1900',
				between_street_1: '19',
				between_street_2: '20',
			},
			emergency_contact_name: 'Lucía Márquez',
			emergency_contact_phone: '+54 9 221 777 3344',
		},
		{
			first_name: 'Paula',
			last_name: 'Morales',
			document_type: 'DNI',
			document_number: '53871246',
			birth_date: '1997-04-23',
			phone: '+54 9 223 111 5555',
			address: {
				country: 'Argentina',
				city: 'Mar del Plata',
				neighborhood: 'Banfield',
				street: 'Castelli',
				number: '745',
				floor: '2',
				unit: 'B',
				additional: 'Frente al mar',
				postal_code: '7600',
				between_street_1: 'Avenida Luro',
				between_street_2: 'Falucho',
			},
			emergency_contact_name: 'Esteban Morales',
			emergency_contact_phone: '+54 9 223 222 6666',
		},
		{
			first_name: 'Bruno',
			last_name: 'Díaz',
			document_type: 'DNI',
			document_number: '65781234',
			birth_date: '1988-12-02',
			phone: '+54 9 11 9900 3344',
			address: {
				country: 'Argentina',
				city: 'Córdoba',
				neighborhood: 'General Paz',
				street: 'Av. Colón',
				number: '1444',
				floor: '5',
				unit: 'E',
				additional: 'Apto 5E',
				postal_code: '5000',
				between_street_1: 'Av. Libertador',
				between_street_2: 'Av. Sabattini',
			},
			emergency_contact_name: 'Mónica Díaz',
			emergency_contact_phone: '+54 9 351 333 7788',
		},
		{
			first_name: 'Laura',
			last_name: 'Ríos',
			document_type: 'CI',
			document_number: '9078561',
			birth_date: '1994-06-11',
			phone: '+54 9 11 1212 3434',
			address: {
				country: 'Argentina',
				city: 'San Miguel de Tucumán',
				neighborhood: 'Centro',
				street: '24 de Septiembre',
				number: '345',
				floor: '4',
				unit: 'A',
				additional: 'Edificio A',
				postal_code: '4000',
				between_street_1: 'Sarmiento',
				between_street_2: 'Mendoza',
			},
			emergency_contact_name: 'Hugo Ríos',
			emergency_contact_phone: '+54 9 381 777 9999',
		},
		{
			first_name: 'Agustín',
			last_name: 'García',
			document_type: 'DNI',
			document_number: '24813579',
			birth_date: '1982-09-04',
			phone: '+54 9 11 2323 4545',
			address: {
				country: 'Argentina',
				city: 'Buenos Aires',
				neighborhood: 'Belgrano',
				street: 'Crisólogo Larralde',
				number: '1235',
				floor: '6',
				unit: 'B',
				additional: 'Depto. 6B',
				postal_code: '1428',
				between_street_1: 'La Pampa',
				between_street_2: 'Vermont',
			},
			emergency_contact_name: 'Marina García',
			emergency_contact_phone: '+54 9 11 4545 6767',
		},
		{
			first_name: 'Martín',
			last_name: 'Alonso',
			document_type: 'DNI',
			document_number: '39487561',
			birth_date: '1999-08-27',
			phone: '+54 9 11 8787 9898',
			address: {
				country: 'Argentina',
				city: 'Santa Fe',
				neighborhood: 'Barrio Roma',
				street: 'Av. Freyre',
				number: '1540',
				floor: '1',
				unit: 'C',
				additional: 'Apto 1C',
				postal_code: '3000',
				between_street_1: 'Av. Aristóbulo del Valle',
				between_street_2: 'Av. Galicia',
			},
			emergency_contact_name: 'Patricia Alonso',
			emergency_contact_phone: '+54 9 342 555 1100',
		},
		{
			first_name: 'Julieta',
			last_name: 'Navarro',
			document_type: 'DNI',
			document_number: '43018762',
			birth_date: '1996-03-31',
			phone: '+54 9 11 6767 4545',
			address: {
				country: 'Argentina',
				city: 'Córdoba',
				neighborhood: 'Cerro de las Rosas',
				street: 'Avenida Rafael Núñez',
				number: '3850',
				floor: '3',
				unit: 'E',
				additional: 'Piso 3',
				postal_code: '5000',
				between_street_1: 'Sucre',
				between_street_2: 'Rondeau',
			},
			emergency_contact_name: 'Marcos Navarro',
			emergency_contact_phone: '+54 9 351 555 3344',
		},
		{
			first_name: 'Esteban',
			last_name: 'Herrera',
			document_type: 'DNI',
			document_number: '58742316',
			birth_date: '1980-07-07',
			phone: '+54 9 261 444 2233',
			address: {
				country: 'Argentina',
				city: 'Mendoza',
				neighborhood: 'Ciudad',
				street: '9 de Julio',
				number: '1120',
				floor: '2',
				unit: 'A',
				additional: 'Departamento 2A',
				postal_code: '5500',
				between_street_1: 'Sarmiento',
				between_street_2: 'Mitre',
			},
			emergency_contact_name: 'Gabriela Herrera',
			emergency_contact_phone: '+54 9 261 333 7788',
		},
		{
			first_name: 'Paola',
			last_name: 'Castro',
			document_type: 'DNI',
			document_number: '64921837',
			birth_date: '1991-01-21',
			phone: '+54 9 11 4455 6677',
			address: {
				country: 'Argentina',
				city: 'Buenos Aires',
				neighborhood: 'Caballito',
				street: 'Rivadavia',
				number: '5200',
				floor: '12',
				unit: 'A',
				additional: 'Piso 12',
				postal_code: '1426',
				between_street_1: 'Av. La Plata',
				between_street_2: 'Av. San Martín',
			},
			emergency_contact_name: 'Víctor Castro',
			emergency_contact_phone: '+54 9 11 2233 1199',
		},
		{
			first_name: 'Natalia',
			last_name: 'Ortiz',
			document_type: 'DNI',
			document_number: '78321549',
			birth_date: '1998-10-29',
			phone: '+54 9 223 9900 2211',
			address: {
				country: 'Argentina',
				city: 'Mar del Plata',
				neighborhood: 'Bº San Carlos',
				street: 'Av. Colón',
				number: '2850',
				floor: '4',
				unit: 'C',
				additional: 'Apto. 4C',
				postal_code: '7600',
				between_street_1: 'Rondeau',
				between_street_2: 'Fleming',
			},
			emergency_contact_name: 'Gustavo Ortiz',
			emergency_contact_phone: '+54 9 223 222 3344',
		},
		{
			first_name: 'Jorge',
			last_name: 'Velázquez',
			document_type: 'DNI',
			document_number: '96541238',
			birth_date: '1985-11-11',
			phone: '+54 9 11 5566 7788',
			address: {
				country: 'Argentina',
				city: 'Santa Fe',
				neighborhood: 'Barrio Roma',
				street: 'Av. Freyre',
				number: '1650',
				floor: '3',
				unit: 'B',
				additional: 'Apto. 3B',
				postal_code: '3000',
				between_street_1: 'Av. Aristóbulo del Valle',
				between_street_2: 'Av. Galicia',
			},
			emergency_contact_name: 'Silvia Velázquez',
			emergency_contact_phone: '+54 9 342 666 8899',
		},
		{
			first_name: 'Camila',
			last_name: 'Ferrer',
			document_type: 'DNI',
			document_number: '25739841',
			birth_date: '1990-09-19',
			phone: '+54 9 11 8899 2233',
			address: {
				country: 'Argentina',
				city: 'Córdoba',
				neighborhood: 'General Paz',
				street: 'Av. Vélez Sarsfield',
				number: '2100',
				floor: '5',
				unit: 'D',
				additional: 'Departamento 5D',
				postal_code: '5000',
				between_street_1: 'Av. Hipólito Yrigoyen',
				between_street_2: 'Av. Colón',
			},
			emergency_contact_name: 'Lucas Ferrer',
			emergency_contact_phone: '+54 9 351 444 1122',
		},
		{
			first_name: 'Ricardo',
			last_name: 'Suárez',
			document_type: 'DNI',
			document_number: '31876524',
			birth_date: '1984-05-08',
			phone: '+54 9 11 4433 2211',
			address: {
				country: 'Argentina',
				city: 'Mar del Plata',
				neighborhood: 'Los Troncos',
				street: 'Av. Colón',
				number: '2255',
				floor: '6',
				unit: 'A',
				additional: 'Piso 6',
				postal_code: '7600',
				between_street_1: 'Av. Luro',
				between_street_2: 'Moreno',
			},
			emergency_contact_name: 'Claudia Suárez',
			emergency_contact_phone: '+54 9 223 777 1100',
		},
		{
			first_name: 'Sandra',
			last_name: 'Paz',
			document_type: 'DNI',
			document_number: '54098712',
			birth_date: '1992-07-16',
			phone: '+54 9 11 3344 5566',
			address: {
				country: 'Argentina',
				city: 'Santa Fe',
				neighborhood: 'Centro',
				street: 'Córdoba',
				number: '438',
				floor: '2',
				unit: 'B',
				additional: 'Depto. 2B',
				postal_code: '3000',
				between_street_1: 'San Martín',
				between_street_2: '1 de Mayo',
			},
			emergency_contact_name: 'Raúl Paz',
			emergency_contact_phone: '+54 9 342 111 3344',
		},
		{
			first_name: 'Tamara',
			last_name: 'Álvarez',
			document_type: 'DNI',
			document_number: '69842135',
			birth_date: '1993-11-02',
			phone: '+54 9 11 5566 8844',
			address: {
				country: 'Argentina',
				city: 'Buenos Aires',
				neighborhood: 'Villa Crespo',
				street: 'Corrientes',
				number: '2800',
				floor: '3',
				unit: 'E',
				additional: 'Piso 3',
				postal_code: '1414',
				between_street_1: 'Scalabrini Ortiz',
				between_street_2: 'Araoz',
			},
			emergency_contact_name: 'Marcelo Álvarez',
			emergency_contact_phone: '+54 9 11 1199 2233',
		}
	];

	await Person.bulkCreate(persons, { individualHooks: true });
};