extension=core

files_impl=\
src/core_role_impl.sql,\
src/core_permission_impl.sql,\
src/core_email_impl.sql,\
src/core_person_impl.sql,\

files_fns=\
src/core_role_fns.sql,\
src/core_permission_fns.sql,\
src/core_person_fns.sql,\
